baseURL = "http://localhost:1313/"
title = "wroot"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minos"
disqusShortname = "wroot"

paginate = 10
smartToc = true
enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "^(build|hack|tweak|pwn|secur)ing$"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["webfonts/ptserif/main.css","webfonts/source-code-pro/main.css",]
customJS = [""]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "wroot.org"
startYear = "2015"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = false
accentColor = "#44ccff"
hideMainMenu = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "jseidl" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "jseidl@wroot.org"
github = "jseidl"

[params.comments]
enable = true

[params.search]
client = "fuse" # algolia / fuse / lunr

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

# Top Menu Entries

[[menu.main]]
name = "About"
weight = 1
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Talks"
weight = 2
identifier = "talks"
url = "/talks/"

[[menu.main]]
name = "Projects"
weight = 3
identifier = "projects"
url = "/projects/"

[[menu.main]]
name = "Press"
weight = 4
identifier = "press"
url = "/press/"

[[menu.main]]
name = "Twitter"
weight = 10
identifier = "twitter"
url = "https://twitter.com/jseidl"

[[menu.main]]
name = "LinkedIn"
weight = 11
identifier = "linkedin"
url = "https://www.linkedin.com/in/janseidl"

[[menu.main]]
name = "GitHub"
weight = 12
identifier = "github"
url = "http://github.com/jseidl"

[[menu.main]]
name = "SlideShare"
weight = 13
identifier = "slideshare"
url = "http://www.slideshare.net/jseidl/"

[[menu.main]]
name = "About"
weight = -10
identifier = "about"
url = "/about/"


[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
